### ISSUE TITLE
compile error with opencv

### ISSUE THREAD

**Issue by northeastsquare** [domoritz/label_generator#1]
Hello When I compile your darknet fork , I got many errors as the original repository. It looks: .cu files compiled lower layer with cpp, but calls darknet c files, and darknet c files call opencv file having c++ template with "extern c". Since "extern c", c compiler cann't compile c++ template, so the errors come. 
Have you met this? Since darknet github have no issues, and you success compiling darknet witch opencv, so I come to you for help. Any hints are appreciated, thank you.
Errors as follows:
nvcc -arch=sm_35 `pkg-config --cflags opencv` -I/usr/local/cuda/include/ -DGPU --compiler-options "-Wall -Wfatal-errors -O3 -DGPU" -c ./src/convolutional_kernels.cu -o obj/convolutional_kernels.o
/usr/local/lib/gcc/x86_64-unknown-linux-gnu/4.7.4/../../../../include/c++/4.7.4/bits/stl_relops.h(86): error: this declaration may not have extern "C" linkage

/usr/local/lib/gcc/x86_64-unknown-linux-gnu/4.7.4/../../../../include/c++/4.7.4/bits/stl_relops.h(99): error: this declaration may not have extern "C" linkage

**Comment by domoritz** [comment]
Hmm, odd. Do you get the same errors when you compile https://github.com/pjreddie/darknet/pulls? What OS are you using? How did you install opencv? Do you have the nvidia driver? Can you compile other opencv code?

**Comment by northeastsquare** [comment]
Do you get the same errors when you compile https://github.com/pjreddie/darknet/pulls? 
Yes, I got the same error.

What OS are you using?
Ubuntu14.04.

How did you install opencv? 
mkdir -p build
cd build
cmake -D BUILD_TIFF=ON -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_TBB=ON -D BUILD_NEW_PYTHON_SUPPORT=ON -D WITH_V4L=ON -D INSTALL_C_EXAMPLES=ON -D INSTALL_PYTHON_EXAMPLES=ON -D BUILD_EXAMPLES=ON -D WITH_QT=ON -D WITH_OPENGL=ON ..
make -j 4
sudo make install
sudo sh -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/opencv.conf'
sudo ldconfig

Do you have the nvidia driver?
I have the nvidia driver, cpu and gpu mode are OK without Opencv option.

Can you compile other opencv code?
I can compile other opencv code.

**Comment by domoritz** [comment]
So we had to run 

``` sh
export PATH=/usr/local/cuda/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
```

before compiling the code but I don't really see what else may be necessary. @pjreddie may be able to help if you report this issue at https://github.com/pjreddie/darknet

**Comment by northeastsquare** [comment]
If in makefile "opencv=0", everything goes well
If "opencv=1",  nvcc compile error
After add the two exports,  error goes the same. 
There is no issue in https://github.com/pjreddie/darknet.

**Comment by domoritz** [comment]
Hmm, ups. Yeah, let's see what @pjreddie suggests.

**Comment by northeastsquare** [comment]
degrade opencv from 3.0 to 2.4, fix it. Thank you
