### ISSUE TITLE
Word segmentation from extracted text-lines

### ISSUE THREAD

**Issue by ghost** [domoritz/label_generator#6]
@domoritz Thank you for your hard work.
My question is, How to segment the words from text-lines?

![000000](https://user-images.githubusercontent.com/33478216/45157653-73ea5200-b1ea-11e8-885b-bc8c111a2156.png)

**Comment by domoritz** [comment]
I'm not sure I understand the question. Can you describe it a bit more? Is this related to something I wrote?

**Comment by ghost** [comment]
@domoritz I have some text-lines that I want to detect the words within them. Example:

![1](https://user-images.githubusercontent.com/33478216/45173538-2a612d80-b211-11e8-8f90-093494956692.jpg)
![2](https://user-images.githubusercontent.com/33478216/45173543-32b96880-b211-11e8-8af0-fd03794f8b7e.jpg)

**Comment by domoritz** [comment]
Ohhhh, I see. I just called tesseract. See https://github.com/tesseract-ocr/tesseract.

**Comment by ghost** [comment]
@domoritz I don't want to recognize the text! but I need to segment the words in the line.
My question is how to train a model to detect words in lines, only detection. for me later on to extract.
![000000](https://user-images.githubusercontent.com/33478216/45175742-d5281a80-b216-11e8-8057-223e83a33446.png)
![000002](https://user-images.githubusercontent.com/33478216/45175745-d5c0b100-b216-11e8-902d-ec14e6bb9d6f.png)
![000003](https://user-images.githubusercontent.com/33478216/45175747-d6594780-b216-11e8-879f-0deb3de121c1.png)
![000004](https://user-images.githubusercontent.com/33478216/45175750-d6f1de00-b216-11e8-8310-44508927cec5.png)
![000005](https://user-images.githubusercontent.com/33478216/45175752-d78a7480-b216-11e8-8b5e-ba27e651e058.png)
![000006](https://user-images.githubusercontent.com/33478216/45175753-d8230b00-b216-11e8-8fa6-3b6f76bec93a.png)
![000007](https://user-images.githubusercontent.com/33478216/45175756-d8bba180-b216-11e8-8773-75ae1db78001.png)
![000008](https://user-images.githubusercontent.com/33478216/45175757-d9543800-b216-11e8-9478-d76088ee7e70.png)
![000009](https://user-images.githubusercontent.com/33478216/45175759-d9543800-b216-11e8-9bf7-e76535cf327f.png)
![000010](https://user-images.githubusercontent.com/33478216/45175760-d9ecce80-b216-11e8-8c9f-16ed28ff069b.png)
![000011](https://user-images.githubusercontent.com/33478216/45175761-da856500-b216-11e8-83a9-1a03a13f16ae.png)
![000012](https://user-images.githubusercontent.com/33478216/45175764-db1dfb80-b216-11e8-8b31-62bbf8af6f7a.png)

**Comment by domoritz** [comment]
I see. My code actually doesn't segment words but tries to fit boxes around pixels that are marked as text. It won't be very reliable for what you want to do. The relevant code starts at https://github.com/domoritz/label_generator/blob/master/predict.py#L99. I recommend that you find your own approach for this problem.

**Comment by ghost** [comment]
any suggestions on which tool should i use? perhaps available on github.

**Comment by domoritz** [comment]
I'm not very familiar with the space, no.
