### ISSUE TITLE
s3 bucket data path --- Documentation issue?

### ISSUE THREAD

**Issue by david-morris** [domoritz/label_generator#8]
I'd like to download the pre-calculated ground truth data in the `s3://escience.washington.edu/viziometrics` bucket.  I've already synced `arxiv_April2017/json` and `arxiv_April2017/img`.  I noticed that the only coordinates in the json files I've seen in the json folder are for the figure instead of the text, so that seems like it's the output of pdffigures, not label_generator.

Where are the output files stored in the s3 bucket?

**Comment by domoritz** [comment]
See https://github.com/domoritz/label_generator/blob/57418691db1702a1024257da074d20dc3854cc81/label_gen.py#L175. Do you see the files you're looking for in `text-masked`?

**Comment by david-morris** [comment]
No.  I do not see any files or folders with text-masked in their name in the s3 bucket.  I looked in arxiv_April2017/img/ and json/ locally, as well as looking in text_prediction_models and text_prediction_test.

As that bucket looks like it may have been used for multiple projects, I'd like to make sure I'm only downloading files I need.

Are those images with bounding boxes masked, or expressed as in `testoutput/json/paper-Figure-0.json`?

Does the bucket contained in the readme contain the output of label_generator, or the output of pdffigures so that label_generator can run without pdffigures installed?  If the latter, how does one run label_generator in that mode?

**Comment by david-morris** [comment]
Ah, it looks like they are in other folders.  I'll try to remember to make a pull request on the readme later.

**Comment by domoritz** [comment]
Thanks!
